### PR TITLE
Removed thread-safety considerations for Loan objects

### LINKED ISSUE #31: Thread Safety
When I originally started working on this project I tried to make everything thread-safe but now I believe that's a bit overkill and not actually attainable, especially with dirty-checking and populating values from json.

I'm thinking the only things that need to be thread-safe are the `EncompassRestClient` as well as its properties and sub-properties.

I don't think objects like `Loan`, `LoanAttachment`, or `LoanDocument` need to be thread-safe.

Any thoughts?

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Closes #31.

### CODE REVIEW

**Comment by TylerBrinkley** [comment]
Still working on this. Don't review yet.

**Comment by TylerBrinkley** [comment]
@hfcjweinstock I've submitted another commit for attachments and documents. Please review that commit as well.

**Comment by hfcjweinstock** [comment]
Reviewed the additional changes. I see you fixed some bugs as well for collections that might be null.

**Comment by TylerBrinkley** [comment]
Yep. Merging.

**Pull request merged**
