### PR TITLE
Changed NA to directly support null values.

### LINKED ISSUE #111: when setting a value to nullthere is no way to clear isDirty to remove serialization.
if you take an existing loan and want to clear the GUID, there is no way to remove the isDirty flag from the EncompassID .  this causes  a rest exception.

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Changed NA to directly support null values.

Fixes #111

### CODE REVIEW

**Comment by TylerBrinkley** [comment]
I'm not sure I'm entirely sold on this approach. I might change it back so that it uses `Nullable` instead but still fix the issue in #111.

**Comment by hfcjweinstock** [comment]
there is no way to set a value to NA

**Comment by TylerBrinkley** [comment]
In this PR? Sure there is. You can call `new NA<decimal>("na")` or simply set it equal to `"NA"` since strings are implicitly convertible to `NA<decimal>`.

**Comment by hfcjweinstock** [comment]
ok, i see what my problem was.... you can pass "frog" in and it will still read NA

**Comment by TylerBrinkley** [comment]
Yeah, I suppose we should throw an exception then?

**Comment by hfcjweinstock** [comment]
also, what values of NA would be allowed? NA, na, N/A etc...i also think this is hte right way to go vs. nullable NA because all other custom types are not "nullable". NA is not a native type and therefore should natively support null.

**Comment by hfcjweinstock** [comment]
id say ignore my frog issue for now.  not sure id call it a bug, more like a thing to worry about when someone complains.

**Comment by TylerBrinkley** [comment]
The potential responses in the json are `null`, `"NA"`, and a number as a string such as `"18.5"`. The reason I'm hesitant about natively supporting null in `NA` is that users have to know about the `IsNull` property on `NA` versus just being able to compare with null such as `value != null` or `value.HasValue`.

**Comment by TylerBrinkley** [comment]
Perhaps we can just add a `HasValue` property?

**Comment by TylerBrinkley** [comment]
I added a `HasValue` property to match `Nullable`.

**Pull request merged**
